<?php
namespace api\version\v10\models;

class MessagesSend extends \yii\base\Model{

    public $to_user_id,$type,$content,$src;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['to_user_id','type','content','src'],'required'],
            [['to_user_id','type'], 'integer'],
            [['src'], 'string', 'max' => 200],
            [['content'], 'string', 'max' => 2000],
        ];
    }

    /**
     * @return array
     * @Author 七秒记忆 <274397981@qq.com>
     * @Date 2020/6/13 14:00
     */
    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios['content'] = ['to_user_id','type','content'];
        $scenarios['src']     = ['to_user_id','type','src'];
        return $scenarios; // TODO: Change the autogenerated stub
    }

}
