<?php
namespace api\version\v10\controllers;
use yii\rest\ActiveController;


/**
 * Index controller
 */
class IndexController extends ActiveController
{
    public $modelClass = 'api\version\v10\models\Apps';


    public function actions()
    {
        $action =  parent::actions(); // TODO: Change the autogenerated stub
        unset($action['index']);
        return $action;
    }
  /*  public function actionIndex(){
            return ['ddd'=>'111111111'];
    }*/
  public function actionIndex(){
      echo 'fdsf';
      return ['fdsf'];
  }
}
