<?php
namespace api\version\v10\controllers;
use api\version\v10\models\MessagesSend;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;

/**
 * Site controller
 */
class MessagesController extends BaseController
{
    public $modelClass = 'api\version\v10\models\Messages';

    public function actions()
    {
        $actions =  parent::actions(); // TODO: Change the autogenerated stub
        unset($actions['index']);
        //unset($actions['index']);
        return $actions;
    }

    public function actionIndex(){


    }

    public function actionSned(){
        $model = new MessagesSend();
        $data  = Yii::$app->request->post();
        $model->to_user_id  = $data['to_user_id'];
        $model->type        = $data['type'];
        $model->content     = $data['content'];
        $model->src         = $data['src'];
        if($data['type'] == 1){
            $model->scenario = 'content';
        }else{
            $model->scenario = 'src';
        }
        if($model->validate()){
            $data = [
                'channel'       => 'push-message',
                'flag'          => 'msg',
                'sign'          =>  Yii::$app->websocket->signValidationKey,
                'to_user_id'    => $model->to_user_id,
                'from_user_id'  => Yii::$app->user->identity->getId(),
                'msg_type'      => $model->type,
                'content'       => $model->content,
                'src'           => $model->src,
            ];
            Yii::$app->websocket->send($data);
            return ['status'=>'success'];
        }else{
            return $model;
        }
    }
}
